services:
  frontend:
    image: dalmiamanhv/sensai-frontend:latest
    container_name: frontend-prod
    ports:
      - "8501:3000" # Standard Next.js dev port
    depends_on:
      - backend
    # restart: unless-stopped
    networks:
      - sensai-network-prod

  backend:
    image: dalmiamanhv/sensai-ai:v2
    container_name: backend-prod
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.main:app --host 0.0.0.0 --port 8001"
    volumes:
      - /appdata:/appdata
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - sensai-network-prod

networks:
  sensai-network-prod:
    driver: bridge
